package morse

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/rivo/tview"
)

type IWRWord struct {
	TargetWord  string
	MatchAny    bool
	StrokeCount int
}

type IWRManager struct {
	WordMap       map[string]*IWRWord
	App           *tview.Application
	StatusMessage string
	IWREnabled    bool
}

var (
	sharedManager *IWRManager
	NonIWRCount   int
	StartTime     time.Time
	PauseStart    time.Time
	TotalPaused   time.Duration
	isFirstRun    bool = true
	IsStopping    bool
)

func SetManager(m *IWRManager) {
	sharedManager = m
}

func GetManager() *IWRManager {
	return sharedManager
}

func (m *IWRManager) LoadIWRFile() (bool, error) {
	var maxIwrLen = 20
	var maxIwrCount = 500
	var file *os.File
	var err error
	var foundPath string
	var fallbackPath string

	// 1. Setup the AppData fallback path
	if docDir, errDir := os.UserConfigDir(); errDir == nil {
		fallbackPath = filepath.Join(docDir, "YAMA", "yamaIWR.txt")
	}

	// 2. Try the local file first (Highest Priority)
	localPath := "./yamaIWR.txt"
	file, err = os.Open(localPath)

	if err == nil {
		foundPath = localPath
	} else if fallbackPath != "" {
		// Failed
		// 3. If local fails, try opening the AppData version
		file, err = os.Open(fallbackPath)
		if err == nil {
			foundPath = fallbackPath
			isFirstRun = true
		} else {
			// 4. If AppData also fails (missing), generate the default!
			if createErr := createDefaultIWRFile(fallbackPath); createErr == nil {
				file, err = os.Open(fallbackPath)
				if err == nil {
					foundPath = fallbackPath
				}
			}
		}
	}

	// 5. Final safety check before continuing
	if err != nil || file == nil {
		m.StatusMessage = "yamaIWR.txt not found and could not be generated"
		time.Sleep(700 * time.Millisecond)
		if err != nil {
			return false, err
		}
		return false, fmt.Errorf("file handle is nil")
	}

	defer file.Close()

	scanner := bufio.NewScanner(file)
	tempMap := make(map[string]*IWRWord)
	cnt := 0

	for scanner.Scan() {
		lineText := strings.TrimSpace(scanner.Text())
		if lineText == "" || strings.HasPrefix(lineText, "#") {
			continue
		}

		for _, word := range strings.Fields(lineText) {
			if len(word) > maxIwrLen {
				continue
			}

			// 1. Isolate the wildcard
			matchAny := strings.HasSuffix(word, "*")
			word = strings.TrimSuffix(word, "*")

			// 2. Wash through the token-aware funnel
			word = ProcessMorseString(word)
			word = strings.TrimSpace(word)
			isValid := len(word) > 0

			// 3. Debug and Assignment
			if isValid {
				tempMap[word] = &IWRWord{
					TargetWord: word,
					MatchAny:   matchAny,
				}
				cnt++
			}

			if cnt >= maxIwrCount {
				break
			}
		}
		if cnt >= maxIwrCount {
			break
		}
	}

	m.WordMap = tempMap
	m.StatusMessage = fmt.Sprintf("Loaded %d words from %s", cnt, foundPath)
	return isFirstRun, nil
}

/* WDL
func (m *IWRManager) ResetSessionStats() {
	NonIWRCount = 0
	StartTime = time.Now()
	TotalPaused = 0
	for _, word := range m.WordMap {
		word.StrokeCount = 0
	}
}
*/

func (m *IWRManager) Match(word string) bool {
	// Everything is already clean and uppercase, so just check the map instantly!
	_, exists := m.WordMap[word]
	return exists
}

/* WDL
// You can drop this helper function near your IWR loading logic
func getIWRFilePath() string {
	localPath := "yamaIWR.txt"

	// 1. Check the local working directory first
	if _, err := os.Stat(localPath); err == nil {
		//log.Printf("Found local IWR file: %s", localPath)
		return localPath
	}

	// 2. Fallback to the AppData location if local doesn't exist
	appDataDir, _ := os.UserConfigDir()
	appDataPath := filepath.Join(appDataDir, "Yama", "yamaIWR.txt")

	//log.Printf("Local file not found, defaulting to AppData: %s", appDataPath)
	return appDataPath
}
*/

func createDefaultIWRFile(filePath string) error {
	// Ensure the directory actually exists before we try to write to it
	dir := filepath.Dir(filePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// Your app-friendly preamble and sample data
	defaultContent := `# This is a SAMPLE yamaIWR.txt file generated by YAMA.
# See the Help info (Ctrl-H) for more about the IWR settings.
#
# IWR "words" or strings to match against your input text are listed below.
# 1 word per line, case does not matter.
# Lines beginning with a '#' are ignored, so they can be used for notes,
# or to temporarily eliminate an entry rather than editing the word out.
#
# Words are for an exact match to input, with 1 exception: an asterisk '*'
# following a word is a shorthand to match any one of the following: .,?:
# Example: QRZ* matches QRZ, QRZ., QRZ,, QRZ?, or QRZ:
#
# --- Sample Entries ---
the
QSL*
W1AW
<SOS>
`
	// Write the file (0644 means readable by anyone, writable by the user)
	return os.WriteFile(filePath, []byte(defaultContent), 0644)
}
